registerBook("Unit3.pdf", {
  icon: "📗",
  desc: "統測單字區第3週",
  badge: "Unit3",
  content: [
    "expert n.專家 adj.熟練的",
    "average n.平均 adj.平均的",
    "frequent adj.頻繁的",
    "individual n.個人 adj.個別的",
    "pressure n.壓力",
    "mental adj.心理的",
    "muscle n.肌肉",
    "stretch v.伸展 n.伸展",
    "regular adj.規律的",
    "proper adj.適當的",
    "physical adj.身體的;物理的",
    "technique n.技巧;技術",
    "condition n.狀況;條件",
    "prevent v.預防;阻止",
    "improve v.改善;增進",
    "positive adj.正面的;積極的",
    "negative adj.負面的;消極的",
    "distance n.距離",
    "process n.過程 v.加工",
    "material n.材料;原料",
    "product n.產品",
    "quality n.品質;特質",
    "quantity n.數量",
    "standard n.標準 adj.標準的",
    "modern adj.現代的",
    "technology n.科技",
    "system n.系統;體制",
    "environment n.環境",
    "resource n.資源",
    "pollution n.污染"
  ],
});